[package]
name = "simple-tile-renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "^0.27.0"
raw-gl-context = "0.1.2"
gl = "0.14.0"
image = "0.19.0"